---
# Settings Config File
host:
    powercap:
        name: power_cap
        type: i
        default: 0
        min: 0
        max: 1000
        unit: watts
    bootflags:
        name: boot_flags
        type: s
        default: "default"
    sysstate:
        name: system_state
        type: s
        default: ""
